version: '3'

services:
  mysql:
    container_name: mysql
    image: arm64v8/mysql:latest  # for other archs, use mysql:latest
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql